version: "3.8"
services:
  frontend-api:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite:///frontend.db
    depends_on:
      - rabbitmq

  backend-api:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - DB_URL=mysql://root:password@db:3306/backend
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backend
    ports:
      - "3306:3306"
