version: "3.8"
services:
  frontend-api:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/frontend
    depends_on:
      - mongo
      - rabbitmq

  backend-api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/backend
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
